// ============================================================
// DriftGuard — Complete 83-Control Governance Data
// 12 Domains × 83 Controls × 14+ Frameworks
// ============================================================

export interface Control {
  id: string;
  name: string;
  description: string;
  domain: string;
  domainCode: string;
  frameworks: string[];
  riskLevel: 'critical' | 'high' | 'medium' | 'low';
  guidance: string;
}

export interface ControlAssessment {
  controlId: string;
  status: 'pass' | 'warn' | 'block' | 'pending' | 'na';
  owner: string;
  lastAssessed: string;
  evidenceCount: number;
  notes?: string;
}

export interface Domain {
  code: string;
  name: string;
  description: string;
  icon: string;
  controlCount: number;
}

// ── DOMAINS ─────────────────────────────────────────────────
export const DOMAINS: Domain[] = [
  { code: 'GL', name: 'Governance & Leadership', description: 'AI governance policy, roles, strategic alignment, asset registry, and risk classification', icon: 'Crown', controlCount: 5 },
  { code: 'RM', name: 'Risk Management', description: 'AI risk framework, identification, treatment, monitoring, bias assessment, and blast radius', icon: 'AlertTriangle', controlCount: 6 },
  { code: 'RO', name: 'Regulatory Operations', description: 'Framework-specific compliance controls across SOC2, GDPR, HIPAA, EU AI Act, and regional standards', icon: 'Scale', controlCount: 15 },
  { code: 'LC', name: 'System, Data & Model Lifecycle', description: 'Version control, prompt governance, training data quality, model cards, and change management', icon: 'GitBranch', controlCount: 7 },
  { code: 'SE', name: 'Security', description: 'AI security architecture, access control, prompt injection defense, and adversarial testing', icon: 'Shield', controlCount: 8 },
  { code: 'PR', name: 'Privacy', description: 'Privacy-by-design, PII detection, right to explanation, and data subject rights', icon: 'Eye', controlCount: 6 },
  { code: 'RS', name: 'Safe & Responsible AI', description: 'Human oversight, hallucination detection, behavioral fingerprinting, drift detection, and bias monitoring', icon: 'ShieldCheck', controlCount: 10 },
  { code: 'AA', name: 'Assurance & Audit', description: 'Internal assessment, independent audit, red teaming, regression testing, and conformity evidence', icon: 'FileCheck', controlCount: 5 },
  { code: 'OM', name: 'Operational Monitoring', description: 'Performance monitoring, anomaly detection, cost intelligence, ROI measurement, and shadow AI', icon: 'Activity', controlCount: 8 },
  { code: 'IM', name: 'Incident Management', description: 'Incident detection, response, reporting, root cause analysis, and rollback controls', icon: 'Siren', controlCount: 5 },
  { code: 'TP', name: 'Third Party & Supply Chain', description: 'Vendor risk assessment, third-party API governance, supply chain transparency, and SLA tracking', icon: 'Package', controlCount: 4 },
  { code: 'CO', name: 'Transparency & Communication', description: 'AI system disclosure, stakeholder engagement, regulatory reporting, and ethics policy', icon: 'Megaphone', controlCount: 4 },
];

// ── ALL 83 CONTROLS ─────────────────────────────────────────
export const CONTROLS: Control[] = [
  // ── DOMAIN 1: Governance & Leadership (GL) — 5 controls ──
  { id: 'GL-01', name: 'AI Governance Policy & Executive Commitment', domain: 'Governance & Leadership', domainCode: 'GL', frameworks: ['ISO42001', 'NIST AI RMF', 'EU AI Act'], riskLevel: 'critical', description: 'Establish and maintain a board-approved AI governance policy with executive sponsorship and defined accountability structures.', guidance: 'Ensure the AI governance policy is reviewed annually and signed off by the board or C-suite. Include measurable objectives and resource commitments.' },
  { id: 'GL-02', name: 'AI Roles & Responsibilities (RACI)', domain: 'Governance & Leadership', domainCode: 'GL', frameworks: ['ISO42001', 'SOC2', 'EU AI Act'], riskLevel: 'high', description: 'Define clear RACI matrix for AI development, deployment, monitoring, and decommissioning across all organizational functions.', guidance: 'Map roles to each AI lifecycle phase. Ensure segregation of duties between development and approval functions.' },
  { id: 'GL-03', name: 'AI Strategic Alignment & Ethical Principles', domain: 'Governance & Leadership', domainCode: 'GL', frameworks: ['ISO42001', 'NIST AI RMF'], riskLevel: 'medium', description: 'Ensure all AI initiatives are aligned with organizational strategy and adhere to published ethical principles.', guidance: 'Publish ethical AI principles. Review all new AI projects against strategic objectives before approval.' },
  { id: 'GL-04', name: 'AI Asset Registry (Model Inventory)', domain: 'Governance & Leadership', domainCode: 'GL', frameworks: ['EU AI Act', 'ISO42001'], riskLevel: 'critical', description: 'Maintain a comprehensive, up-to-date registry of all AI systems including models, datasets, and endpoints deployed across the organization.', guidance: 'Automate discovery of AI assets. Include model provider, version, deployment environment, data sources, and risk classification for each entry.' },
  { id: 'GL-05', name: 'AI Risk Classification (High/Limited/Minimal)', domain: 'Governance & Leadership', domainCode: 'GL', frameworks: ['EU AI Act', 'NIST AI RMF'], riskLevel: 'critical', description: 'Classify every AI system according to its risk level per EU AI Act categories and internal risk appetite.', guidance: 'Apply the EU AI Act risk tier system. High-risk systems require conformity assessment and ongoing monitoring.' },

  // ── DOMAIN 2: Risk Management (RM) — 6 controls ──────────
  { id: 'RM-01', name: 'AI Risk Management Framework Setup', domain: 'Risk Management', domainCode: 'RM', frameworks: ['NIST AI RMF', 'ISO42001'], riskLevel: 'critical', description: 'Establish a formal AI risk management framework aligned with organizational risk appetite and industry standards.', guidance: 'Adopt NIST AI RMF GOVERN function. Define risk appetite thresholds for AI behavioral metrics.' },
  { id: 'RM-02', name: 'AI Risk Identification & Assessment', domain: 'Risk Management', domainCode: 'RM', frameworks: ['NIST AI RMF', 'EU AI Act', 'ISO42001'], riskLevel: 'high', description: 'Systematically identify, document, and assess risks associated with each AI system across technical, ethical, and operational dimensions.', guidance: 'Conduct risk assessments at project inception and each major version update. Use structured taxonomy for AI-specific risks.' },
  { id: 'RM-03', name: 'AI Risk Treatment & Mitigation Plans', domain: 'Risk Management', domainCode: 'RM', frameworks: ['NIST AI RMF', 'ISO42001'], riskLevel: 'high', description: 'Develop and implement risk treatment plans for identified AI risks, with clear mitigation strategies and residual risk acceptance.', guidance: 'Document treatment options: avoid, mitigate, transfer, accept. Track mitigation actions to completion.' },
  { id: 'RM-04', name: 'Continuous AI Risk Monitoring', domain: 'Risk Management', domainCode: 'RM', frameworks: ['NIST AI RMF', 'SOC2'], riskLevel: 'high', description: 'Implement continuous monitoring of AI risk indicators including behavioral drift, performance degradation, and compliance gaps.', guidance: 'Set up automated alerts for risk threshold breaches. Review risk dashboard weekly.' },
  { id: 'RM-05', name: 'Bias & Fairness Risk Assessment', domain: 'Risk Management', domainCode: 'RM', frameworks: ['EU AI Act', 'NIST AI RMF'], riskLevel: 'critical', description: 'Assess and mitigate bias risks across all AI systems, with particular focus on protected characteristics and equitable outcomes.', guidance: 'Run fairness audits on training data and model outputs. Document demographic parity metrics.' },
  { id: 'RM-06', name: 'AI Blast Radius Assessment', domain: 'Risk Management', domainCode: 'RM', frameworks: ['NIST AI RMF'], riskLevel: 'high', description: 'Evaluate the potential impact scope of AI system failures or misbehavior, including downstream dependencies and user exposure.', guidance: 'Map all systems and users affected by each AI endpoint. Define blast radius tiers and corresponding containment procedures.' },

  // ── DOMAIN 3: Regulatory Operations (RO) — 15 controls ───
  { id: 'RO-01', name: 'SOC2 AI Controls (CC6/CC7/CC8)', domain: 'Regulatory Operations', domainCode: 'RO', frameworks: ['SOC2'], riskLevel: 'critical', description: 'Implement and evidence SOC2 trust services criteria controls specific to AI systems.', guidance: 'Map AI-specific controls to CC6 (access), CC7 (operations), CC8 (change management). Collect evidence continuously.' },
  { id: 'RO-02', name: 'GDPR AI Compliance (Art.22 Automated Decisions)', domain: 'Regulatory Operations', domainCode: 'RO', frameworks: ['GDPR'], riskLevel: 'critical', description: 'Ensure all AI-driven automated decision-making complies with GDPR Article 22 requirements for human oversight and explanation.', guidance: 'Identify all automated decision points. Implement opt-out mechanisms and meaningful information about the logic involved.' },
  { id: 'RO-03', name: 'HIPAA AI Controls (PHI in LLM Context)', domain: 'Regulatory Operations', domainCode: 'RO', frameworks: ['HIPAA'], riskLevel: 'critical', description: 'Prevent protected health information from being exposed through AI system context windows, training data, or outputs.', guidance: 'Implement PHI detection and masking in all AI pipelines. Ensure BAA coverage for AI vendors processing PHI.' },
  { id: 'RO-04', name: 'EU AI Act Conformity Assessment', domain: 'Regulatory Operations', domainCode: 'RO', frameworks: ['EU AI Act'], riskLevel: 'critical', description: 'Conduct and maintain conformity assessments for all high-risk AI systems per EU AI Act requirements.', guidance: 'Complete technical documentation per Article 11. Conduct internal conformity assessment per Article 43.' },
  { id: 'RO-05', name: 'NIST AI RMF Profile Documentation', domain: 'Regulatory Operations', domainCode: 'RO', frameworks: ['NIST AI RMF'], riskLevel: 'high', description: 'Create and maintain NIST AI RMF organizational profile documenting current and target risk management practices.', guidance: 'Map current practices to GOVERN, MAP, MEASURE, MANAGE functions. Identify gaps and remediation timelines.' },
  { id: 'RO-06', name: 'ISO 42001 AI Management System', domain: 'Regulatory Operations', domainCode: 'RO', frameworks: ['ISO42001'], riskLevel: 'high', description: 'Implement and maintain an AI management system conforming to ISO 42001 requirements.', guidance: 'Address all ISO 42001 clauses. Conduct internal audits annually. Prepare for certification audit.' },
  { id: 'RO-07', name: 'ISO 27001 Information Security for AI', domain: 'Regulatory Operations', domainCode: 'RO', frameworks: ['ISO27001'], riskLevel: 'high', description: 'Extend ISO 27001 ISMS controls to cover AI-specific information security risks.', guidance: 'Add AI-specific controls to Annex A. Address model security, training data protection, and inference security.' },
  { id: 'RO-08', name: 'MAS AI Governance Framework (APAC)', domain: 'Regulatory Operations', domainCode: 'RO', frameworks: ['MAS'], riskLevel: 'high', description: 'Comply with Monetary Authority of Singapore guidelines on AI governance for financial services.', guidance: 'Implement FEAT principles: Fairness, Ethics, Accountability, Transparency. Document compliance evidence.' },
  { id: 'RO-09', name: 'APRA CPS 234 AI Controls (Australia)', domain: 'Regulatory Operations', domainCode: 'RO', frameworks: ['APRA'], riskLevel: 'high', description: 'Ensure AI systems meet APRA CPS 234 information security requirements for regulated Australian entities.', guidance: 'Classify AI information assets. Implement controls commensurate with criticality and sensitivity.' },
  { id: 'RO-10', name: 'BCBS 239 AI Model Data Lineage (Banking)', domain: 'Regulatory Operations', domainCode: 'RO', frameworks: ['BCBS 239'], riskLevel: 'high', description: 'Maintain complete data lineage for AI models used in banking risk reporting per BCBS 239 principles.', guidance: 'Document data flows from source to model to report. Ensure accuracy, completeness, and timeliness of risk data.' },
  { id: 'RO-11', name: 'BNM AI Governance (Malaysia)', domain: 'Regulatory Operations', domainCode: 'RO', frameworks: ['BNM RMiT'], riskLevel: 'medium', description: 'Comply with Bank Negara Malaysia requirements for AI governance in financial services.', guidance: 'Align with BNM RMiT guidelines for technology risk management in AI systems.' },
  { id: 'RO-12', name: 'OJK AI Governance (Indonesia)', domain: 'Regulatory Operations', domainCode: 'RO', frameworks: ['OJK'], riskLevel: 'medium', description: 'Comply with OJK requirements for AI governance in Indonesian financial services.', guidance: 'Implement OJK-mandated AI governance controls for digital financial services.' },
  { id: 'RO-13', name: 'PCI-DSS AI Controls (Payment Data in AI)', domain: 'Regulatory Operations', domainCode: 'RO', frameworks: ['PCI-DSS'], riskLevel: 'critical', description: 'Prevent payment card data from being processed or exposed through AI systems without PCI-DSS compliant controls.', guidance: 'Implement data masking for cardholder data in AI pipelines. Ensure PCI-DSS scope includes AI processing environments.' },
  { id: 'RO-14', name: 'DORA AI Operational Resilience (EU Finance)', domain: 'Regulatory Operations', domainCode: 'RO', frameworks: ['DORA'], riskLevel: 'high', description: 'Ensure AI systems meet Digital Operational Resilience Act requirements for EU financial entities.', guidance: 'Include AI systems in ICT risk management framework. Test AI resilience scenarios annually.' },
  { id: 'RO-15', name: 'Audit-Ready Compliance Report Generation', domain: 'Regulatory Operations', domainCode: 'RO', frameworks: ['ISO42001', 'SOC2', 'EU AI Act', 'GDPR', 'HIPAA'], riskLevel: 'high', description: 'Generate comprehensive, audit-ready compliance reports across all applicable frameworks with evidence packages.', guidance: 'Automate report generation. Include control status, evidence links, assessment history, and gap analysis.' },

  // ── DOMAIN 4: System, Data & Model Lifecycle (LC) — 7 ────
  { id: 'LC-01', name: 'AI Model Version Control & Changelog', domain: 'System, Data & Model Lifecycle', domainCode: 'LC', frameworks: ['ISO42001', 'EU AI Act'], riskLevel: 'high', description: 'Maintain version control for all AI models with detailed changelogs documenting behavioral and technical changes.', guidance: 'Use semantic versioning. Document prompt changes, model swaps, and fine-tuning updates with behavioral impact analysis.' },
  { id: 'LC-02', name: 'Prompt Version Control & Approval', domain: 'System, Data & Model Lifecycle', domainCode: 'LC', frameworks: ['ISO42001', 'NIST AI RMF'], riskLevel: 'high', description: 'Version-control all system prompts with formal approval workflows for production changes.', guidance: 'Store prompts in version control. Require peer review and behavioral diff before production deployment.' },
  { id: 'LC-03', name: 'Training Data Quality & Governance', domain: 'System, Data & Model Lifecycle', domainCode: 'LC', frameworks: ['ISO42001', 'GDPR'], riskLevel: 'critical', description: 'Ensure training data quality, provenance tracking, and compliance with data protection regulations.', guidance: 'Document data sources, licensing, and consent. Run data quality checks before training. Maintain data lineage records.' },
  { id: 'LC-04', name: 'Model Card & Technical Documentation', domain: 'System, Data & Model Lifecycle', domainCode: 'LC', frameworks: ['EU AI Act', 'ISO42001'], riskLevel: 'high', description: 'Create and maintain model cards with technical documentation for every AI system including intended use, limitations, and performance metrics.', guidance: 'Follow EU AI Act Article 11 technical documentation requirements. Update model cards with each version release.' },
  { id: 'LC-05', name: 'AI System Change Management', domain: 'System, Data & Model Lifecycle', domainCode: 'LC', frameworks: ['ISO42001', 'SOC2', 'EU AI Act'], riskLevel: 'high', description: 'Implement formal change management processes for AI system modifications including impact assessment and rollback procedures.', guidance: 'Require change requests with behavioral impact assessment. Implement staged rollouts with automated rollback capability.' },
  { id: 'LC-06', name: 'AI System Retirement & Decommission Policy', domain: 'System, Data & Model Lifecycle', domainCode: 'LC', frameworks: ['ISO42001', 'EU AI Act'], riskLevel: 'medium', description: 'Define and execute formal retirement and decommissioning procedures for AI systems including data disposal and stakeholder notification.', guidance: 'Notify affected stakeholders 90 days before retirement. Ensure proper data disposal and audit trail preservation.' },
  { id: 'LC-07', name: 'Data Contract for AI Inputs & Outputs', domain: 'System, Data & Model Lifecycle', domainCode: 'LC', frameworks: ['BCBS 239'], riskLevel: 'medium', description: 'Establish formal data contracts defining expected schemas, quality requirements, and SLAs for AI system inputs and outputs.', guidance: 'Define data contracts with schema validation, null checks, and freshness requirements. Monitor contract violations.' },

  // ── DOMAIN 5: Security (SE) — 8 controls ─────────────────
  { id: 'SE-01', name: 'AI Security Architecture & Threat Model', domain: 'Security', domainCode: 'SE', frameworks: ['ISO27001', 'NIST AI RMF', 'SOC2'], riskLevel: 'critical', description: 'Design and maintain a security architecture for AI systems with comprehensive threat modeling covering AI-specific attack vectors.', guidance: 'Conduct threat modeling using STRIDE or MITRE ATLAS. Address prompt injection, data poisoning, model extraction, and inference attacks.' },
  { id: 'SE-02', name: 'AI Access Control & RBAC', domain: 'Security', domainCode: 'SE', frameworks: ['SOC2', 'ISO27001', 'EU AI Act'], riskLevel: 'critical', description: 'Implement role-based access control for AI systems with least-privilege principles and regular access reviews.', guidance: 'Define roles: Admin, Manager, Engineer, Auditor, Viewer. Enforce RBAC on all API endpoints and UI features.' },
  { id: 'SE-03', name: 'Prompt Injection Defense', domain: 'Security', domainCode: 'SE', frameworks: ['OWASP LLM Top10', 'NIST AI RMF'], riskLevel: 'critical', description: 'Implement defenses against direct and indirect prompt injection attacks across all AI endpoints.', guidance: 'Deploy input sanitization, output filtering, and instruction hierarchy. Run automated prompt injection test suites.' },
  { id: 'SE-04', name: 'Jailbreak & Adversarial Probe Testing', domain: 'Security', domainCode: 'SE', frameworks: ['OWASP LLM Top10', 'EU AI Act'], riskLevel: 'critical', description: 'Regularly test AI systems against jailbreak attempts and adversarial probes to validate safety boundaries.', guidance: 'Run DriftGuard probe suites including DAN, roleplay, encoding, and social engineering attack vectors.' },
  { id: 'SE-05', name: 'Model Tampering & Poisoning Protection', domain: 'Security', domainCode: 'SE', frameworks: ['NIST AI RMF', 'ISO27001'], riskLevel: 'high', description: 'Protect AI models from tampering, weight manipulation, and training data poisoning attacks.', guidance: 'Implement model integrity verification. Monitor for unexpected behavioral changes that may indicate poisoning.' },
  { id: 'SE-06', name: 'AI Agent Action Security & Blast Radius', domain: 'Security', domainCode: 'SE', frameworks: ['NIST AI RMF'], riskLevel: 'critical', description: 'Constrain AI agent actions to approved scopes with blast radius limits and human-in-the-loop for high-impact operations.', guidance: 'Define action allowlists per agent. Implement confirmation gates for destructive or financial actions.' },
  { id: 'SE-07', name: 'Network & API Security for AI Endpoints', domain: 'Security', domainCode: 'SE', frameworks: ['ISO27001', 'SOC2', 'DORA'], riskLevel: 'high', description: 'Secure AI endpoint communications with encryption, rate limiting, authentication, and network segmentation.', guidance: 'Enforce TLS 1.3 minimum. Implement API key rotation, rate limiting, and IP allowlisting for production endpoints.' },
  { id: 'SE-08', name: 'AI Secrets & Credential Management', domain: 'Security', domainCode: 'SE', frameworks: ['SOC2', 'ISO27001'], riskLevel: 'critical', description: 'Securely manage API keys, model access tokens, and other credentials used by AI systems.', guidance: 'Use secrets management (Vault, AWS Secrets Manager). Never embed credentials in prompts or code. Rotate credentials quarterly.' },

  // ── DOMAIN 6: Privacy (PR) — 6 controls ──────────────────
  { id: 'PR-01', name: 'Privacy-by-Design for AI Systems', domain: 'Privacy', domainCode: 'PR', frameworks: ['GDPR', 'ISO27701'], riskLevel: 'high', description: 'Embed privacy-by-design principles into all AI system development and deployment processes.', guidance: 'Conduct privacy reviews at design phase. Implement data minimization, purpose limitation, and storage limitation.' },
  { id: 'PR-02', name: 'PII Detection & Masking in AI Outputs', domain: 'Privacy', domainCode: 'PR', frameworks: ['GDPR', 'HIPAA', 'SOC2'], riskLevel: 'critical', description: 'Detect and mask personally identifiable information in AI system inputs, outputs, and logs.', guidance: 'Deploy regex and NER-based PII detection. Mask emails, SSNs, credit cards, phone numbers, and addresses in all outputs.' },
  { id: 'PR-03', name: 'Right to Explanation (AI Decisions)', domain: 'Privacy', domainCode: 'PR', frameworks: ['GDPR', 'EU AI Act'], riskLevel: 'high', description: 'Provide meaningful explanations for AI-driven decisions that significantly affect individuals.', guidance: 'Implement explainability features for high-impact decisions. Document the logic, significance, and consequences of AI processing.' },
  { id: 'PR-04', name: 'Data Subject Rights in AI Context', domain: 'Privacy', domainCode: 'PR', frameworks: ['GDPR'], riskLevel: 'high', description: 'Enable exercise of data subject rights (access, rectification, erasure, portability) for personal data processed by AI systems.', guidance: 'Implement data subject request workflows covering AI training data, inference logs, and behavioral profiles.' },
  { id: 'PR-05', name: 'Personal Data in LLM Context Window', domain: 'Privacy', domainCode: 'PR', frameworks: ['GDPR', 'HIPAA'], riskLevel: 'critical', description: 'Prevent unauthorized personal data from being included in LLM context windows and ensure data minimization.', guidance: 'Implement context window scanning. Strip PII before sending to external LLM providers. Log data flows for audit.' },
  { id: 'PR-06', name: 'Privacy Impact Assessment for AI', domain: 'Privacy', domainCode: 'PR', frameworks: ['GDPR', 'ISO27701'], riskLevel: 'high', description: 'Conduct Data Protection Impact Assessments (DPIA) for AI systems processing personal data at scale.', guidance: 'Complete DPIA before deploying AI systems processing sensitive data. Review annually or when processing changes significantly.' },

  // ── DOMAIN 7: Safe & Responsible AI (RS) — 10 controls ───
  { id: 'RS-01', name: 'Human Oversight & Override Controls', domain: 'Safe & Responsible AI', domainCode: 'RS', frameworks: ['EU AI Act', 'NIST AI RMF'], riskLevel: 'critical', description: 'Implement human oversight mechanisms with the ability to override, intervene, or halt AI system operations.', guidance: 'Implement kill switches for high-risk AI. Require human approval for consequential AI decisions. Log all overrides.' },
  { id: 'RS-02', name: 'Hallucination Detection & Scoring', domain: 'Safe & Responsible AI', domainCode: 'RS', frameworks: ['NIST AI RMF', 'EU AI Act'], riskLevel: 'critical', description: 'Detect, measure, and score hallucination rates across all AI system outputs with trending and alerting.', guidance: 'Use DriftGuard hallucination scoring engine. Set thresholds per endpoint. Alert when scores exceed acceptable limits.' },
  { id: 'RS-03', name: 'Behavioral Fingerprinting Engine', domain: 'Safe & Responsible AI', domainCode: 'RS', frameworks: ['NIST AI RMF', 'ISO42001'], riskLevel: 'high', description: 'Generate behavioral fingerprints for each AI system version across 8 dimensions to establish behavioral baselines.', guidance: 'Fingerprint dimensions: Hallucination, Refusal Rate, Tone, Semantic Consistency, Topic Consistency, Latency, Token Efficiency, Output Quality.' },
  { id: 'RS-04', name: 'Behavioral Drift Detection (Diff Engine)', domain: 'Safe & Responsible AI', domainCode: 'RS', frameworks: ['NIST AI RMF'], riskLevel: 'high', description: 'Detect and quantify behavioral changes between AI system versions using automated diff analysis.', guidance: 'Compare fingerprints across versions. Flag regressions exceeding configured thresholds. Require review for WARN/BLOCK verdicts.' },
  { id: 'RS-05', name: 'AI Output Explainability & Transparency', domain: 'Safe & Responsible AI', domainCode: 'RS', frameworks: ['EU AI Act', 'ISO42001'], riskLevel: 'high', description: 'Provide transparent, interpretable explanations for AI system outputs and decision processes.', guidance: 'Implement attribution tracking, confidence scores, and source citation where applicable.' },
  { id: 'RS-06', name: 'Bias Detection & Fairness Monitoring', domain: 'Safe & Responsible AI', domainCode: 'RS', frameworks: ['EU AI Act', 'NIST AI RMF'], riskLevel: 'critical', description: 'Continuously monitor AI outputs for demographic bias, unfair treatment, and discriminatory patterns.', guidance: 'Run fairness metrics across protected groups. Test with diverse evaluation datasets. Alert on disparity threshold breaches.' },
  { id: 'RS-07', name: 'Tone & Communication Consistency', domain: 'Safe & Responsible AI', domainCode: 'RS', frameworks: ['ISO42001'], riskLevel: 'medium', description: 'Monitor and maintain consistent communication tone across AI system outputs aligned with brand and regulatory requirements.', guidance: 'Track formal/casual/technical/empathetic tone ratios. Alert on tone drift exceeding 15% from baseline.' },
  { id: 'RS-08', name: 'Refusal Rate Monitoring', domain: 'Safe & Responsible AI', domainCode: 'RS', frameworks: ['NIST AI RMF'], riskLevel: 'medium', description: 'Monitor AI system refusal rates to ensure appropriate safety boundaries without excessive false refusals.', guidance: 'Track refusal rate by category. Investigate spikes above 5% baseline. Balance safety with usability.' },
  { id: 'RS-09', name: 'Semantic Consistency Scoring', domain: 'Safe & Responsible AI', domainCode: 'RS', frameworks: ['ISO42001'], riskLevel: 'medium', description: 'Score and monitor semantic consistency of AI outputs to ensure reliable, reproducible responses across similar queries.', guidance: 'Use embedding similarity to measure consistency. Alert when semantic variance exceeds threshold for production endpoints.' },
  { id: 'RS-10', name: 'Off-Topic & Scope Drift Detection', domain: 'Safe & Responsible AI', domainCode: 'RS', frameworks: ['EU AI Act'], riskLevel: 'medium', description: 'Detect when AI systems generate responses outside their defined scope or topic boundaries.', guidance: 'Define topic boundaries per endpoint. Monitor off-topic response rates. Implement guardrails for scope enforcement.' },

  // ── DOMAIN 8: Assurance & Audit (AA) — 5 controls ────────
  { id: 'AA-01', name: 'Internal AI Governance Assessment', domain: 'Assurance & Audit', domainCode: 'AA', frameworks: ['ISO42001', 'SOC2', 'NIST AI RMF'], riskLevel: 'high', description: 'Conduct regular internal assessments of AI governance effectiveness across all controls and domains.', guidance: 'Assess quarterly. Use structured questionnaires. Report findings to governance board. Track remediation actions.' },
  { id: 'AA-02', name: 'Independent AI Audit & Certification', domain: 'Assurance & Audit', domainCode: 'AA', frameworks: ['ISO42001', 'EU AI Act'], riskLevel: 'high', description: 'Engage independent third parties for AI system audits and certification assessments.', guidance: 'Schedule annual independent audits. Select auditors with AI governance expertise. Maintain certification currency.' },
  { id: 'AA-03', name: 'Adversarial Safety Validation (Red Teaming)', domain: 'Assurance & Audit', domainCode: 'AA', frameworks: ['NIST AI RMF', 'OWASP LLM Top10'], riskLevel: 'critical', description: 'Conduct adversarial red teaming exercises to validate AI system safety and security boundaries.', guidance: 'Run quarterly red team exercises. Include prompt injection, jailbreak, data extraction, and social engineering vectors.' },
  { id: 'AA-04', name: 'Regression Testing & Benchmark Datasets', domain: 'Assurance & Audit', domainCode: 'AA', frameworks: ['ISO42001', 'NIST AI RMF'], riskLevel: 'high', description: 'Maintain benchmark datasets and run regression tests against every AI system update before production deployment.', guidance: 'Build golden datasets per endpoint. Run regression suite as part of deployment pipeline. Block deployment on regression.' },
  { id: 'AA-05', name: 'Conformity Assessment Evidence Package', domain: 'Assurance & Audit', domainCode: 'AA', frameworks: ['EU AI Act', 'ISO42001'], riskLevel: 'high', description: 'Compile and maintain complete evidence packages supporting conformity assessments for all applicable frameworks.', guidance: 'Organize evidence by framework and control. Ensure evidence is current (within 12 months). Include automated and manual evidence.' },

  // ── DOMAIN 9: Operational Monitoring (OM) — 8 controls ───
  { id: 'OM-01', name: 'AI Performance Monitoring (Latency/Uptime)', domain: 'Operational Monitoring', domainCode: 'OM', frameworks: ['SOC2', 'NIST AI RMF'], riskLevel: 'high', description: 'Monitor AI system performance metrics including latency, throughput, uptime, and error rates.', guidance: 'Set SLOs for latency (p50, p95, p99), uptime (99.9%), and error rate (<0.1%). Alert on SLO breaches.' },
  { id: 'OM-02', name: 'Behavioral Anomaly Detection & Alerting', domain: 'Operational Monitoring', domainCode: 'OM', frameworks: ['NIST AI RMF'], riskLevel: 'high', description: 'Detect behavioral anomalies in AI system outputs using statistical and ML-based anomaly detection.', guidance: 'Monitor behavioral metrics for sudden shifts. Use z-score and moving average anomaly detection. Alert in real-time.' },
  { id: 'OM-03', name: 'Token Usage & Cost Monitoring', domain: 'Operational Monitoring', domainCode: 'OM', frameworks: [], riskLevel: 'medium', description: 'Track token consumption and associated costs across all AI endpoints in real-time.', guidance: 'Monitor daily token usage per endpoint and model. Set budget alerts at 80% and 100% of monthly allocation.' },
  { id: 'OM-04', name: 'AI Budget Forecasting & Cost Intelligence', domain: 'Operational Monitoring', domainCode: 'OM', frameworks: [], riskLevel: 'medium', description: 'Forecast AI operational costs with scenario analysis and optimization recommendations.', guidance: 'Project monthly and annual costs using historical data. Model worst-case scenarios. Identify cost optimization opportunities.' },
  { id: 'OM-05', name: 'Shadow AI Detection (Unauthorized Tools)', domain: 'Operational Monitoring', domainCode: 'OM', frameworks: ['ISO42001', 'SOC2', 'GDPR'], riskLevel: 'critical', description: 'Detect and catalog unauthorized AI tools and services being used within the organization.', guidance: 'Monitor network traffic for known AI service domains. Survey teams quarterly. Maintain approved AI tool registry.' },
  { id: 'OM-06', name: 'AI ROI Measurement Dashboard', domain: 'Operational Monitoring', domainCode: 'OM', frameworks: [], riskLevel: 'medium', description: 'Measure and visualize return on investment for AI initiatives across departments.', guidance: 'Track hours saved, cost avoided, revenue impact, and quality improvements per AI system. Report quarterly to leadership.' },
  { id: 'OM-07', name: 'Model Recommendation Engine', domain: 'Operational Monitoring', domainCode: 'OM', frameworks: [], riskLevel: 'low', description: 'Recommend optimal AI models for specific use cases based on capability, cost, and compliance requirements.', guidance: 'Maintain model capability matrix. Score models against task requirements. Factor in cost and compliance constraints.' },
  { id: 'OM-08', name: 'Continuous Improvement Tracking', domain: 'Operational Monitoring', domainCode: 'OM', frameworks: ['ISO42001', 'NIST AI RMF'], riskLevel: 'medium', description: 'Track and report on continuous improvement initiatives for AI governance maturity.', guidance: 'Set annual maturity targets. Track improvement velocity. Report progress to governance board quarterly.' },

  // ── DOMAIN 10: Incident Management (IM) — 5 controls ─────
  { id: 'IM-01', name: 'AI Incident Detection & Response', domain: 'Incident Management', domainCode: 'IM', frameworks: ['ISO42001', 'SOC2', 'EU AI Act'], riskLevel: 'critical', description: 'Detect, classify, and respond to AI-related incidents within defined SLAs.', guidance: 'Define incident severity levels. Set response SLAs: P1=15min, P2=1hr, P3=4hr. Establish incident commander rotation.' },
  { id: 'IM-02', name: 'Serious Incident Reporting (15-day rule)', domain: 'Incident Management', domainCode: 'IM', frameworks: ['EU AI Act'], riskLevel: 'critical', description: 'Report serious AI incidents to relevant authorities within 15 days per EU AI Act Article 73 requirements.', guidance: 'Define serious incident criteria. Automate incident assessment against reporting thresholds. Prepare regulatory notification templates.' },
  { id: 'IM-03', name: 'AI Incident Root Cause Analysis', domain: 'Incident Management', domainCode: 'IM', frameworks: ['ISO42001', 'NIST AI RMF'], riskLevel: 'high', description: 'Conduct thorough root cause analysis for all AI incidents with documented findings and preventive actions.', guidance: 'Use 5-whys and fishbone analysis. Document root cause, contributing factors, and corrective actions. Track action completion.' },
  { id: 'IM-04', name: 'AI Incident Audit Log (Immutable)', domain: 'Incident Management', domainCode: 'IM', frameworks: ['EU AI Act', 'SOC2', 'ISO27001'], riskLevel: 'critical', description: 'Maintain immutable audit logs of all AI system events, changes, incidents, and administrative actions.', guidance: 'Use append-only storage. Include timestamp, actor, action, and result. Retain for minimum 5 years. Prevent log tampering.' },
  { id: 'IM-05', name: 'Rollback & Version Revert Controls', domain: 'Incident Management', domainCode: 'IM', frameworks: ['ISO42001', 'NIST AI RMF'], riskLevel: 'high', description: 'Implement rapid rollback capabilities to revert AI systems to known-good versions during incidents.', guidance: 'Maintain last 3 known-good versions. Test rollback procedures quarterly. Achieve rollback within 5 minutes for P1 incidents.' },

  // ── DOMAIN 11: Third Party & Supply Chain (TP) — 4 ────────
  { id: 'TP-01', name: 'AI Vendor & Foundation Model Risk Assessment', domain: 'Third Party & Supply Chain', domainCode: 'TP', frameworks: ['ISO42001', 'EU AI Act', 'DORA'], riskLevel: 'critical', description: 'Assess and manage risks associated with AI vendors and foundation model providers.', guidance: 'Evaluate vendor security posture, data handling, SLAs, and business continuity. Reassess annually or on contract renewal.' },
  { id: 'TP-02', name: 'Third-Party AI API Governance', domain: 'Third Party & Supply Chain', domainCode: 'TP', frameworks: ['SOC2', 'ISO27001', 'DORA'], riskLevel: 'high', description: 'Govern all third-party AI API integrations with security, compliance, and performance requirements.', guidance: 'Maintain API governance registry. Monitor third-party API availability and performance. Implement fallback providers.' },
  { id: 'TP-03', name: 'AI Supply Chain Transparency', domain: 'Third Party & Supply Chain', domainCode: 'TP', frameworks: ['EU AI Act', 'ISO42001'], riskLevel: 'high', description: 'Maintain transparency about AI supply chain including model provenance, training data sources, and downstream dependencies.', guidance: 'Document model origin, training data sources, and processing locations. Comply with EU AI Act Article 53 transparency obligations.' },
  { id: 'TP-04', name: 'Model Provider SLA & Dependency Tracking', domain: 'Third Party & Supply Chain', domainCode: 'TP', frameworks: ['DORA'], riskLevel: 'medium', description: 'Track and manage SLAs and dependencies on AI model providers to ensure operational resilience.', guidance: 'Monitor provider uptime and latency. Maintain fallback providers for critical endpoints. Test failover annually.' },

  // ── DOMAIN 12: Transparency & Communication (CO) — 4 ─────
  { id: 'CO-01', name: 'AI System Disclosure to End Users', domain: 'Transparency & Communication', domainCode: 'CO', frameworks: ['EU AI Act', 'GDPR'], riskLevel: 'high', description: 'Disclose to end users when they are interacting with or affected by AI systems per regulatory requirements.', guidance: 'Implement clear AI interaction labels. Provide information about AI capabilities and limitations. Comply with EU AI Act Article 13.' },
  { id: 'CO-02', name: 'Stakeholder Communication & Engagement', domain: 'Transparency & Communication', domainCode: 'CO', frameworks: ['ISO42001', 'NIST AI RMF'], riskLevel: 'medium', description: 'Establish regular communication channels with stakeholders about AI governance status, risks, and improvements.', guidance: 'Publish quarterly AI governance reports. Conduct stakeholder briefings. Maintain feedback channels.' },
  { id: 'CO-03', name: 'Regulatory Reporting & Notifications', domain: 'Transparency & Communication', domainCode: 'CO', frameworks: ['EU AI Act', 'MAS', 'APRA', 'OJK', 'BNM RMiT'], riskLevel: 'high', description: 'Submit required regulatory reports and notifications about AI systems to relevant authorities.', guidance: 'Maintain regulatory reporting calendar. Automate report compilation. Track submission deadlines and confirmations.' },
  { id: 'CO-04', name: 'AI Ethics & Responsible Use Policy', domain: 'Transparency & Communication', domainCode: 'CO', frameworks: ['ISO42001', 'NIST AI RMF'], riskLevel: 'medium', description: 'Publish and enforce an AI ethics and responsible use policy covering all organizational AI activities.', guidance: 'Publish policy publicly. Train all employees. Review annually. Include enforcement mechanisms and violation reporting.' },
];

// ── MOCK ASSESSMENTS ────────────────────────────────────────
const OWNERS = ['Sarah Chen', 'Marcus Rivera', 'Priya Patel', 'James O\'Brien', 'Yuki Tanaka', 'Ahmed Hassan'];
const DATES = ['2024-12-15', '2025-01-10', '2025-02-01', '2025-01-22', '2025-02-14', '2025-01-05'];

function generateAssessment(controlId: string, index: number): ControlAssessment {
  const statuses: ControlAssessment['status'][] = ['pass', 'pass', 'pass', 'pass', 'warn', 'warn', 'block', 'pending'];
  const hash = controlId.split('').reduce((a, c) => a + c.charCodeAt(0), 0);
  return {
    controlId,
    status: statuses[(hash + index) % statuses.length],
    owner: OWNERS[(hash + index) % OWNERS.length],
    lastAssessed: DATES[(hash + index) % DATES.length],
    evidenceCount: ((hash * 3 + index) % 8) + 1,
    notes: undefined,
  };
}

export const MOCK_ASSESSMENTS: ControlAssessment[] = CONTROLS.map((c, i) => generateAssessment(c.id, i));

// ── FRAMEWORK LIST ──────────────────────────────────────────
export const FRAMEWORKS = [
  { id: 'soc2',      name: 'SOC2',        fullName: 'SOC 2 Type II',                    color: '#8B5CF6' },
  { id: 'gdpr',      name: 'GDPR',        fullName: 'General Data Protection Regulation', color: '#3B82F6' },
  { id: 'hipaa',     name: 'HIPAA',       fullName: 'Health Insurance Portability Act',   color: '#10B981' },
  { id: 'eu-ai-act', name: 'EU AI Act',   fullName: 'EU Artificial Intelligence Act',     color: '#F59E0B' },
  { id: 'nist',      name: 'NIST AI RMF', fullName: 'NIST AI Risk Management Framework',  color: '#06B6D4' },
  { id: 'iso42001',  name: 'ISO42001',    fullName: 'ISO/IEC 42001 AI Management System', color: '#EC4899' },
  { id: 'iso27001',  name: 'ISO27001',    fullName: 'ISO/IEC 27001 Information Security', color: '#6366F1' },
  { id: 'mas',       name: 'MAS',         fullName: 'MAS AI Governance Framework',        color: '#14B8A6' },
  { id: 'apra',      name: 'APRA',        fullName: 'APRA CPS 234',                      color: '#F97316' },
  { id: 'bcbs',      name: 'BCBS 239',    fullName: 'BCBS 239 Data Lineage',              color: '#84CC16' },
  { id: 'dora',      name: 'DORA',        fullName: 'Digital Operational Resilience Act',  color: '#8B5CF6' },
  { id: 'pci-dss',   name: 'PCI-DSS',     fullName: 'PCI Data Security Standard v4',      color: '#EF4444' },
  { id: 'owasp',     name: 'OWASP LLM Top10', fullName: 'OWASP LLM Top 10',              color: '#EF4444' },
  { id: 'iso27701',  name: 'ISO27701',    fullName: 'ISO 27701 Privacy Information',      color: '#6366F1' },
];
